nip96: upload file
BlowaterNostr/nostr.ts pull request #82
Opened 2024-05-15 13:09 UTC by bob2402

2024-05-15 15:21 UTC, BlowaterNostr requested changes

2024-05-15 15:21 UTC, BlowaterNostr commented on event.ts
> +export async function prepareHttpAuthEvent(
let's move to `nip96.ts`

2024-05-15 15:21 UTC, BlowaterNostr commented on nip96.test.ts
> +    console.log(result);
assert the result instead of logging

2024-05-15 15:21 UTC, BlowaterNostr commented on nip96.test.ts
> +    const file = new Blob([await Deno.readFile("./test.jpeg")], { type: "image/jpeg" });
Let's use an image in the internet instead of committing a file to the git.

2024-05-15 15:21 UTC, BlowaterNostr commented on nip96.ts
> +    return result.json() as Promise<UploadFileResponse>;
Does this endpoint always return 200? If not, need to do traditional status code handling

2024-05-15 15:21 UTC, BlowaterNostr commented on nostr.ts
>      Group_Message = 1000,
let's remove this as well, not used anymore

2024-05-15 15:21 UTC, BlowaterNostr commented on nip96.ts
> +    return result.json() as Promise<UploadFileResponse>;
JSON parse could fail and throw as well.

2024-05-17 12:09 UTC, BlowaterNostr requested changes

2024-05-17 12:09 UTC, BlowaterNostr commented on makefile
> +	deno test --allow-net --trace-leaks --coverage=cov_profile *.test.ts
keep both

2024-05-17 12:09 UTC, BlowaterNostr commented on relayed.ts
> +    system_key: "nsec1geplx78d053a7554j8xtrfgffknukmyc6w206r2dszdsl2t2zhnqw0g3fg",
Why do we need a hard-coded nsec?

2024-05-17 12:09 UTC, BlowaterNostr commented on relayed.ts
Rename to `relayed.test.ts` or `test.relayed.ts` to indicate that it's not a production module

2024-05-17 12:18 UTC, zhengbangbo commented on relay-single-test.ts
> +        if (err4 instanceof Error) fail(err4.message);
Send 4 but receive only 3 to test its limit.

2024-05-17 12:19 UTC, bob2402 commented on relay-single-test.ts
> +        if (err4 instanceof Error) fail(err4.message);
Send 4 but receive only 3 to test its limit.

2024-05-17 13:26 UTC, BlowaterNostr approved these changes

2024-05-17 13:28 UTC, merged